### ISSUE TITLE
Unable to install via composer

### ISSUE THREAD

**Issue by Dimonka2** [laravel/lumen-framework#1184]
- Lumen Version: No idea, latest.
- Laravel Version: The same
- PHP Version: 8.0.7
- Database Driver & Version: no
- Composer version: 2.1.5
- Windows 10, Laragon
### Description:
Following installation step 1 via composer I am constantly getting fatal error:

```
Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php:71
Stack trace:
#0 phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php(71): fclose(false)
#1 phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php(194): Symfony\Component\Process\Pipes\WindowsPipes->__construct(false, NULL)
#2 phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Process.php(1231): Symfony\Component\Process\Pipes\WindowsPipes::create(Object(Symfony\Component\Process\Process), NULL)
#3 phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Process.php(258): Symfony\Component\Process\Process->getDescriptors()
#4 phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Process.php(196): Symfony\Component\Process\Process->start(Array)
#5 phar://C:/Users/...../composer/composer.phar/src/Composer/Util/ProcessExecutor.php(125): Symfony\Component\Process\Process->run(Array)
#6 phar://C:/Users/...../composer/composer.phar/src/Composer/Util/ProcessExecutor.php(65): Composer\Util\ProcessExecutor->doExecute('git branch -a -...', 'C:\\Users\\......', false, NULL)
#7 phar://C:/Users/...../composer/composer.phar/src/Composer/Package/Version/VersionGuesser.php(123): Composer\Util\ProcessExecutor->execute('git branch -a -...', NULL, 'C:\\Users\\......')
#8 phar://C:/Users/...../composer/composer.phar/src/Composer/Package/Version/VersionGuesser.php(72): Composer\Package\Version\VersionGuesser->guessGitVersion(Array, 'C:\\Users\\......')
#9 phar://C:/Users/...../composer/composer.phar/src/Composer/Package/Loader/RootPackageLoader.php(83): Composer\Package\Version\VersionGuesser->guessVersion(Array, 'C:\\Users\\......')
#10 phar://C:/Users/...../composer/composer.phar/src/Composer/Factory.php(368): Composer\Package\Loader\RootPackageLoader->load(Array, 'Composer\\Packag...', 'C:\\Users\\......')
#11 phar://C:/Users/...../composer/composer.phar/src/Composer/Factory.php(595): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false)
#12 phar://C:/Users/...../composer/composer.phar/src/Composer/Command/CreateProjectCommand.php(362): Composer\Factory::create(Object(Composer\IO\ConsoleIO), Array, false)
#13 phar://C:/Users/...../composer/composer.phar/src/Composer/Command/CreateProjectCommand.php(177): Composer\Command\CreateProjectCommand->installRootPackage(Object(Composer\IO\ConsoleIO), Object(Composer\Config), 'laravel/lumen', 'C:\\Users\\......', NULL, 'stable', false, true, true, NULL, false, false, false, false, true)
#14 phar://C:/Users/...../composer/composer.phar/src/Composer/Command/CreateProjectCommand.php(159): Composer\Command\CreateProjectCommand->installProject(Object(Composer\IO\ConsoleIO), Object(Composer\Config), Object(Symfony\Component\Console\Input\ArgvInput), 'laravel/lumen', 'blog', NULL, NULL, false, true, true, NULL, false, false, false, false, false, true, false)
#15 phar://C:/Users/...../composer/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\CreateProjectCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar://C:/Users/...../composer/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar://C:/Users/...../composer/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\CreateProjectCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar://C:/Users/...../composer/composer.phar/src/Composer/Console/Application.php(310): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar://C:/Users/...../composer/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar://C:/Users/...../composer/composer.phar/src/Composer/Console/Application.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 phar://C:/Users/...../composer/composer.phar/bin/composer(63): Composer\Console\Application->run()
#22 C:\Users\...ae\Downloads\laragon\bin\composer\composer.phar(24): require('phar://C:/Users...')
#23 {main}
  thrown in phar://C:/Users/...../composer/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php on line 71

```
### Steps To Reproduce:
In my configuration just type in command line :
```
composer create-project --prefer-dist laravel/lumen blog
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
