### ISSUE TITLE
Lumen Testing that visit or access a route that connects to db result in fatal error

### ISSUE THREAD

**Issue by changwuf31** [laravel/lumen-framework#268]
If we run phpunit on the ExampleTest route '/', everything works.
If we run phpunit on a route, let's say '/user/', which access database to get the user, then the following fatal error occured.

```
Fatal error: Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/container/Container.php:737
Stack trace:
#0 /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/container/Container.php(737): ReflectionClass->__construct('config')
#1 /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/container/Container.php(627): Illuminate\Container\Container->build('config', Array)
#2 /home/wuf31/gitlab/sfs3/tvlumen/vendor/laravel/lumen-framework/src/Application.php(447): Illuminate\Container\Container->make('config', Array)
#3 /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/container/Container.php(1159): Laravel\Lumen\Application->make('config')
#4 /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/database/DatabaseManager.php(251): Illuminate\Container\Container->offsetGet('config')
#5 /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/database/DatabaseManager.php(85): Illuminate\Database\DatabaseManager->getDefaultConnection()
#6 /home/wuf31/gitlab/sfs3/ in /home/wuf31/gitlab/sfs3/tvlumen/vendor/illuminate/container/Container.php on line 737
```

This is found on lumen 5.1.5, with both withFacades enabled or disabled.

**Comment by GrahamCampbell** [comment]
Duplicate.
