### ISSUE TITLE
Moving Laravel 5 application to Lumen - Class path.storage does not exist error

### ISSUE THREAD

**Issue by maliakmal** [laravel/lumen-framework#383]
Hi guys, I'm trying to port my laravel 5 based api application to lumen however its giving me this error consistently and I'm at my wits end on how to solve it. This is the error stack:

```
[Sun Mar 13 14:44:27.424346 2016] [:error] [pid 4683] [client 127.0.0.1:51632] PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class path.storage does not exist' in /home/Projects/api.local/vendor/laravel/framework/src/Illuminate/Container/Container.php:736
Stack trace:
#0 /home/Projects/api.local/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('path.storage')
#1 /home/Projects/api.local/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('path.storage', Array)
#2 /home/Projects/api.local/vendor/laravel/lumen-framework/src/Application.php(203): Illuminate\\Container\\Container->make('path.storage', Array)
#3 /home/Projects/api.local/vendor/laravel/framework/src/Illuminatesearch?utf8=✓&q=path.storage&type=Issues/Foundation/helpers.php(63): Laravel\\Lumen\\Application->make('path.storage', Array)
#4 /home/Projects/api.local/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(633): app('path.storage')
#5 /home/Projects/api.local in /home/Projects/api.local/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 736

```

This is my composer file:
```

    "require": {
        "php": ">=5.5.9",
        "laravel/lumen-framework": "5.2.*",
        "illuminate/support": "5.2.*",
        "vlucas/phpdotenv": "~2.2",
        "cviebrock/eloquent-sluggable": "dev-master",
        "nanigans/single-table-inheritance": "dev-master",
        "kalnoy/nestedset": "dev-master",
        "laravelbook/ardent": "3.*",
        "dingo/api": "1.0.*@dev",
        "codesleeve/laravel-stapler": "1.0.*",
        "laravel/socialite": "^2.0",
        "aws/aws-sdk-php": "2.4.*@dev",
        "sammyk/laravel-facebook-sdk": "^3.0",
        "intervention/image": "^2.3"
    },

```

I've just added some routes to my route file and already I'm facing this error - please how can I fix this?

**Comment by GrahamCampbell** [comment]
Please ask on the forums.

**Comment by GrahamCampbell** [comment]
Looks to me like maybe some of those packages you have don't work on lumen.
