### ISSUE TITLE
Router error on IIS 8.5

### ISSUE THREAD

**Issue by avadaneidanut** [laravel/lumen-framework#397]
After configuring lumen and adding a web.config for IIS 8.5 it'll trigger:
`
[2016-04-06 16:51:06] lumen.ERROR: exception 'ErrorException' with message 'Undefined index: REQUEST_URI' in C:\inetpub\wwwroot\sapxtractor\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php:674
Stack trace:
#0 C:\inetpub\wwwroot\sapxtractor\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(674): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined index...', 'C:\\inetpub\\wwwr...', 674, Array)
#1 C:\inetpub\wwwroot\sapxtractor\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(404): Laravel\Lumen\Application->getPathInfo()
#2 C:\inetpub\wwwroot\sapxtractor\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(371): Laravel\Lumen\Application->parseIncomingRequest(NULL)
#3 C:\inetpub\wwwroot\sapxtractor\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(327): Laravel\Lumen\Application->dispatch(NULL)
#4 C:\inetpub\wwwroot\sapxtractor\public\index.php(28): Laravel\Lumen\Application->run()
#5 {main}  
`
My server indeed doesn't have REQUEST_URI index but I don't have this issue on laravel.

I added this in app.php and it works:
```php
if (isset($_SERVER['HTTP_X_ORIGINAL_URL'])) {
	$_SERVER['REQUEST_URI'] = $_SERVER['HTTP_X_ORIGINAL_URL'];
}
```

**Comment by yuloh** [comment]
Laravel has a [web.config](https://github.com/laravel/laravel/blob/master/public/web.config), maybe Lumen should have one too?

Does the Laravel web.config works with Lumen without the app.php change?
