### ISSUE TITLE
Route group cause Target ResponseFactory is not instantiable 

### ISSUE THREAD

**Issue by ihsanberahim** [laravel/lumen-framework#572]
```
[2017-02-17 07:15:39] lumen.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable. in /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
Stack trace:
#0 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Container/Container.php(687): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Container/Container.php(565): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/developer/Documents/Project/vendor/laravel/lumen-framework/src/Application.php(208): Illuminate\Container\Container->make('Illuminate\\Cont...')
#3 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(105): Laravel\Lumen\Application->make('Illuminate\\Cont...')
#4 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(715): app('Illuminate\\Cont...')
#5 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(195): response()
#6 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(173): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#7 /Users/developer/Documents/Project/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(119): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#8 /Users/developer/Documents/Project/app/Exceptions/Handler.php(50): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#9 /Users/developer/Documents/Project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(105): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#10 /Users/developer/Documents/Project/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(536): Laravel\Lumen\Application->sendExceptionToHandler(Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#11 /Users/developer/Documents/Project/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#12 /Users/developer/Documents/Project/api/public/index.php(28): Laravel\Lumen\Application->run()
#13 /Users/developer/.composer/vendor/laravel/valet/server.php(128): require('/Users/developer...')
#14 {main}  
```

This error only happen if i use `$app->group`
```
$app->group(['prefix' => 'v1'], function ($app) {
    require __DIR__.'/routes/api-v1.php';
});
```

No error if i just use
```
$app->get('/', function () use ($app) {
    return $app->version();
});
```

**Comment by ihsanberahim** [comment]
Sorry. This is my bad.
i created group v1 but i access the base.
