### ISSUE TITLE
Misleading exception in Container for parse errors

### ISSUE THREAD

**Issue by razvanphp** [laravel/lumen-framework#591]
When there is a typo in the class definition, for example `constt` instead of `const`, the fatal exception message is very misleading, it just says the class does not exist.

`Class Iris\\Modules\\Navigation\\Repositories\\CategoryRepository does not exist`

stack trace:
```
Next ReflectionException: Class Iris\Modules\Navigation\Repositories\CategoryRepository does not exist in /home/vagrant/backend/vendor/illuminate/container/Container.php:731
Stack trace:
#0 /home/vagrant/backend/vendor/illuminate/container/Container.php(731): ReflectionParameter->getClass()
#1 /home/vagrant/backend/vendor/illuminate/container/Container.php(708): Illuminate\Container\Container->resolveDependencies(Array)
#2 /home/vagrant/backend/vendor/illuminate/container/Container.php(565): Illuminate\Container\Container->build('Iris\\Modules\\Na...')
#3 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Application.php(208): Illuminate\Container\Container->make('Iris\\Modules\\Na...')
#4 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(676): Laravel\Lumen\Application->make('Iris\\Modules\\Na...')
#5 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#6 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(628): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#7 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(598): Laravel\Lumen\Application->handleFoundRoute(Array)
#8 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(532): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#9 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Iris\Http\Request))
#10 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Iris\Http\Request))
#11 /home/vagrant/backend/app/Middleware/CorsMiddleware.php(24): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Iris\Http\Request))
#12 /home/vagrant/backend/vendor/illuminate/pipeline/Pipeline.php(148): Iris\Middleware\CorsMiddleware->handle(Object(Iris\Http\Request), Object(Closure))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Iris\Http\Request))
#14 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Iris\Http\Request))
#15 /home/vagrant/backend/app/Middleware/JWTMiddleware.php(61): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Iris\Http\Request))
#16 /home/vagrant/backend/vendor/illuminate/pipeline/Pipeline.php(148): Iris\Middleware\JWTMiddleware->handle(Object(Iris\Http\Request), Object(Closure))
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Iris\Http\Request))
#18 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Iris\Http\Request))
#19 /home/vagrant/backend/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Iris\Http\Request))
#20 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#22 /home/vagrant/backend/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#23 /home/vagrant/backend/public/index.php(28): Laravel\Lumen\Application->run()
#24 {main}  
```

Can it maybe show the parse fatal error instead? Strange enough, this happened for us because of incompatibility between php 7.1 and 7.0 and it was very hard to debug.

We're using lumen 5.4.5. Thank you!

**Comment by hakuno** [comment]
My Lumen doesn't even show me any.

Actually, I'm only getting an empty 500 http error.

What about?

**Comment by GrahamCampbell** [comment]
Closing due to inactivity.
