### ISSUE TITLE
php artisan not working

### ISSUE THREAD

**Issue by deividaspetraitis** [laravel/lumen-framework#655]
- Lumen Version: 5.5.x
- PHP Version: PHP 7.1.x
- Database Driver & Version: N/A

### Description:

When I run  `php artisan` I got following exceptions:

```
[2017-09-25 09:45:07] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function Illuminate\Cache\Console\ClearCommand::__construct(), 1 passed in /home/vagrant/Code/xxxp/public_html/vendor/laravel/lumen-framework/src/Console/ConsoleServiceProvider.php on line 113 and exactly 2 expected in /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Cache/Console/ClearCommand.php:48
Stack trace:
#0 /home/vagrant/Code/xxxp/public_html/vendor/laravel/lumen-framework/src/Console/ConsoleServiceProvider.php(113): Illuminate\Cache\Console\ClearCommand->__construct(Object(Illuminate\Cache\CacheManager))
#1 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Laravel\Lumen\Console\ConsoleServiceProvider->Laravel\Lumen\Console\{closure}(Object(Laravel\Lumen\Application), Array)
#2 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('command.cache.c...', Array)
#4 /home/vagrant/Code/xxxp/public_html/vendor/laravel/lumen-framework/src/Application.php(230): Illuminate\Container\Container->make('command.cache.c...', Array)
#5 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(228): Laravel\Lumen\Application->make('command.cache.c...')
#6 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(242): Illuminate\Console\Application->resolve('command.cache.c...')
#7 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(263): Illuminate\Console\Application->resolveCommands(Array)
#8 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(147): Illuminate\Support\ServiceProvider->Illuminate\Support\{closure}(Object(Illuminate\Console\Application))
#9 /home/vagrant/Code/xxxp/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(70): Illuminate\Console\Application->bootstrap()
#10 /home/vagrant/Code/xxxp/public_html/vendor/laravel/lumen-framework/src/Console/Kernel.php(165): Illuminate\Console\Application->__construct(Object(Laravel\Lumen\Application), Object(Illuminate\Events\Dispatcher), 'Lumen (5.5.0) (...')
#11 /home/vagrant/Code/xxxp/public_html/vendor/laravel/lumen-framework/src/Console/Kernel.php(84): Laravel\Lumen\Console\Kernel->getArtisan()
#12 /home/vagrant/Code/xxxp/public_html/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  
```
Problem occured once laravel framework was updated (v5.5.4 => v5.5.13)

Composer.json

```
{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/lumen-framework": "5.5.*",
        "illuminate/mail": "^5.5",
        "vlucas/phpdotenv": "^2.4",
        "barryvdh/laravel-cors": "^0.9.3",
        "tobscure/json-api": "^0.4.1",
        "nwidart/laravel-modules": "^2.1",
        "cartalyst/sentinel": "^2.0",
        "dusterio/lumen-passport": "^0.2.0",
        "kalnoy/nestedset": "^4.3",
        "friendsofphp/php-cs-fixer": "^2.5",
        "s-ichikawa/laravel-sendgrid-driver": "^2.0",
        "laravel/scout": "^3.0",
        "basemkhirat/elasticsearch": "^1.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~6.0",
        "mockery/mockery": "~0.9"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Modules\\": "Modules/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

### Steps To Reproduce:

run: `php artisan`

**Comment by deividaspetraitis** [comment]
Fake alarm. Issue was about mixing laravel and lumens framework dependencies by requiring both in composer.json

**Comment by pkeatingcrossflow** [comment]
I am getting this issue too. I have checked the API docs and the [Illuminate\Cache\Console\ClearCommand](https://laravel.com/api/5.5/Illuminate/Cache/Console/ClearCommand.html) constructor does indeed require two arguments. The registerCacheClearCommand method in Laravel\Lumen\Console\ConsoleServiceProvider is as follows:
`
    /**
     * Register the command.
     *
     * @return void
     */
    protected function registerCacheClearCommand()
    {
        $this->app->singleton('command.cache.clear', function ($app) {
            return new CacheClearCommand($app['cache']);
        });
    }

`

So it looks like an error in the Framework to me. In my opinion, this issue should be re-opened.

**Comment by pkeatingcrossflow** [comment]
The file [Illuminate\Foundation\Providers\ArtisanServiceProvider](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php) on which Lumen's ConsoleServiceProvider is based has the registerCacheClearCommand method defined as follows:
```php
/**
     * Register the command.
     *
     * @return void
     */
    protected function registerCacheClearCommand()
    {
        $this->app->singleton('command.cache.clear', function ($app) {
            return new CacheClearCommand($app['cache'], $app['files']);
        });
    }
```
This change was made 14 days ago to the Laravel repo, and presumably has not percolated down to Lumen yet.

**Comment by deividaspetraitis** [comment]
@pkeatingcrossflow make sure that your project doesn't contain packages that requires both Laravel and Lumen frameworks in composer.js. In such case Laravel dependencies overrides Lumens and that produces such error. Laravel dependency in packages composer.js must be moved to "required-dev" in order to solve this problem. Hope it helps!
