### ISSUE TITLE
Count exception when generating an coverage report in htm.

### ISSUE THREAD

**Issue by agentmarine** [laravel/lumen-framework#773]
- Lumen Version: 5.6.*
- PHP Version: 7.2.5
- Database Driver & Version: N/A

### Description:
Hi Guys, I am getting an error when generating a coverage report in HTML format, Clover XML Format works fine, but the HTML format throws a count() exception when generating.
```
Danss-MacBook-Pro:project dansmacbook$ phpunit
PHPUnit 6.1.4 by Sebastian Bergmann and contributors.

........                                                            8 / 8 (100%)

Time: 10.14 seconds, Memory: 24.00MB

OK (8 tests, 10 assertions)

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ...PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Renderer/File.php:307
Stack trace:
#0 /Users/dansmacbook/Library/project/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'count(): Parame...', 'phar:///usr/loc...', 307, Array)
#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'count(): Parame...', 'phar:///usr/loc...', 307, Array)
#2 phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Renderer/File.php(307): count(NULL)
#3 phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Renderer/File.php(61): SebastianBergmann\CodeCoverage\Report\Html\File->renderSource(Object(SebastianBergmann\CodeCoverage\Node\File))
#4 phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Facade.php(117): SebastianBergmann\CodeCoverage\Report\Html\File->re in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Renderer/File.php on line 307

Fatal error: Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Renderer/File.php on line 307

ErrorException: count(): Parameter must be an array or an object that implements Countable in phar:///usr/local/bin/phpunit/php-code-coverage/Report/Html/Renderer/File.php on line 307

Call Stack:
   10.2695   23273168   1. Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:0
   10.2695   23273168   2. Laravel\Lumen\Application->handleUncaughtException() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:50
   10.2698   23273600   3. Laravel\Lumen\Exceptions\Handler->report() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:122

PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php:767
Stack trace:
#0 /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php(767): ReflectionClass->__construct('config')
#1 /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php(646): Illuminate\Container\Container->build('config')
#2 /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php(601): Illuminate\Container\Container->resolve('config', Array)
#3 /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Application.php(221): Illuminate\Container\Container->make('config', Array)
#4 /Users/dansmacbook/Library/project in /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php on line 767

Fatal error: Uncaught ReflectionException: Class config does not exist in /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php on line 767

ReflectionException: Class config does not exist in /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php on line 767

Call Stack:
   10.2775   23276072   1. Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:0
   10.2775   23276072   2. Laravel\Lumen\Application->handleShutdown() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:54
   10.2795   23294096   3. Laravel\Lumen\Application->handleUncaughtException() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:67
   10.2797   23294176   4. App\Exceptions\Handler->report() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php:122
   10.2797   23294176   5. App\Exceptions\Handler->report() /Users/dansmacbook/Library/project/app/Exceptions/Handler.php:41
   10.2849   23433608   6. Illuminate\Log\LogManager->error() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Exceptions/Handler.php:45
   10.2849   23433608   7. Illuminate\Log\LogManager->driver() /Users/dansmacbook/Library/project/vendor/illuminate/log/LogManager.php:519
   10.2849   23433608   8. Illuminate\Log\LogManager->getDefaultDriver() /Users/dansmacbook/Library/project/vendor/illuminate/log/LogManager.php:103
   10.2849   23433608   9. Laravel\Lumen\Application->offsetGet() /Users/dansmacbook/Library/project/vendor/illuminate/log/LogManager.php:436
   10.2849   23433608  10. Laravel\Lumen\Application->make() /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php:1210
   10.2849   23433608  11. Laravel\Lumen\Application->make() /Users/dansmacbook/Library/project/vendor/laravel/lumen-framework/src/Application.php:221
   10.2849   23433608  12. Laravel\Lumen\Application->resolve() /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php:601
   10.2850   23433608  13. Laravel\Lumen\Application->build() /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php:646
   10.2850   23433720  14. ReflectionClass->__construct() /Users/dansmacbook/Library/project/vendor/illuminate/container/Container.php:767


```

### Steps To Reproduce:

> phpunit.xml

```
    <logging>
        <log type="coverage-clover" target="tests/_reports/logs/clover.xml"/>
        <log type="coverage-html" target="tests/_reports/coverage" charset="UTF-8" yui="true" highlight="true" lowUpperBound="35" highLowerBound="70" />
    <logging>
```
`$ phpunit`

**Comment by xing393939** [comment]
Hi，I have got the same problem with that，what is your solution？My versions is：
php-code-coverage 5.2.2 
PHP 7.3.4 with Xdebug 2.7.2 
PHPUnit 6.2.4
