### ISSUE TITLE
Class 'Ramsey\Uuid\Uuid' not found in /vendor/illuminate/support/Str.php:531

### ISSUE THREAD

**Issue by chimit** [laravel/lumen-framework#785]
- Lumen Version: 5.6.4
- Database Driver & Version: MySQL 5.7

### Description:
This exception is thrown on Notification send. Before upgrading packages to the latest versions it worked without problems.
```
[2018-07-05 04:36:30] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Ramsey\Uuid\Uuid' not found in /home/vagrant/Code/test-api/vendor/illuminate/support/Str.php:531
Stack trace:
#0 /home/vagrant/Code/test-api/vendor/illuminate/notifications/NotificationSender.php(86): Illuminate\Support\Str::uuid()
#1 /home/vagrant/Code/test-api/vendor/illuminate/notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Support\Collection), Object(App\Notifications\MessageCreated))
#2 /home/vagrant/Code/test-api/vendor/illuminate/notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Support\Collection), Object(App\Notifications\MessageCreated))
#3 /home/vagrant/Code/test-api/vendor/illuminate/support/Facades/Facade.php(221): Illuminate\Notifications\ChannelManager->send(Object(Illuminate\Support\Collection), Object(App\Notifications\MessageCreated))
#4 /home/vagrant/Code/test-api/app/Listeners/MessageCreated.php(41): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#5 [internal function]: App\Listeners\MessageCreatedListener->handle(Object(App\Events\MessageCreated))
#6 /home/vagrant/Code/test-api/vendor/illuminate/events/Dispatcher.php(379): call_user_func_array(Array, Array)
#7 /home/vagrant/Code/test-api/vendor/illuminate/events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('App\\Events\\Mess...', Array)
#8 /home/vagrant/Code/test-api/vendor/illuminate/events/Dispatcher.php(182): Illuminate\Events\Dispatcher->dispatch('App\\Events\\Mess...', Array, false)
#9 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/helpers.php(184): Illuminate\Events\Dispatcher->fire(Object(App\Events\MessageCreated), Array, false)
#10 /home/vagrant/Code/test-api/app/Http/Controllers/v1/MessageController.php(31): event(Object(App\Events\MessageCreated))
#11 [internal function]: App\Http\Controllers\v1\MessageController->create(Object(Illuminate\Http\Request))
#12 /home/vagrant/Code/test-api/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /home/vagrant/Code/test-api/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /home/vagrant/Code/test-api/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#15 /home/vagrant/Code/test-api/vendor/illuminate/container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#16 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\Container\Container->call(Array, Array)
#17 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#18 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\v1\MessageController), 'create', Array)
#19 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\Lumen\Application->callControllerAction(Array)
#20 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(255): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#21 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#22 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home/vagrant/Code/test-api/app/Http/Middleware/AuthMiddleware.php(52): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(151): App\Http\Middleware\AuthMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure), 'user')
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /home/vagrant/Code/test-api/vendor/neomerx/cors-illuminate/src/CorsMiddleware.php(67): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(151): Neomerx\CorsIlluminate\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#41 /home/vagrant/Code/test-api/public/index.php(28): Laravel\Lumen\Application->run()
#42 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Ramsey\\Uuid\\Uuid' not found at /home/vagrant/Code/test-api/vendor/illuminate/support/Str.php:531)
[stacktrace]
#0 /home/vagrant/Code/test-api/vendor/illuminate/notifications/NotificationSender.php(86): Illuminate\\Support\\Str::uuid()
#1 /home/vagrant/Code/test-api/vendor/illuminate/notifications/NotificationSender.php(64): Illuminate\\Notifications\\NotificationSender->sendNow(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\MessageCreated))
#2 /home/vagrant/Code/test-api/vendor/illuminate/notifications/ChannelManager.php(35): Illuminate\\Notifications\\NotificationSender->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\MessageCreated))
#3 /home/vagrant/Code/test-api/vendor/illuminate/support/Facades/Facade.php(221): Illuminate\\Notifications\\ChannelManager->send(Object(Illuminate\\Support\\Collection), Object(App\\Notifications\\MessageCreated))
#4 /home/vagrant/Code/test-api/app/Listeners/MessageCreated.php(41): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#5 [internal function]: App\\Listeners\\MessageCreatedListener->handle(Object(App\\Events\\MessageCreated))
#6 /home/vagrant/Code/test-api/vendor/illuminate/events/Dispatcher.php(379): call_user_func_array(Array, Array)
#7 /home/vagrant/Code/test-api/vendor/illuminate/events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('App\\\\Events\\\\Mess...', Array)
#8 /home/vagrant/Code/test-api/vendor/illuminate/events/Dispatcher.php(182): Illuminate\\Events\\Dispatcher->dispatch('App\\\\Events\\\\Mess...', Array, false)
#9 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/helpers.php(184): Illuminate\\Events\\Dispatcher->fire(Object(App\\Events\\MessageCreated), Array, false)
#10 /home/vagrant/Code/test-api/app/Http/Controllers/v1/MessageController.php(31): event(Object(App\\Events\\MessageCreated))
#11 [internal function]: App\\Http\\Controllers\\v1\\MessageController->create(Object(Illuminate\\Http\\Request))
#12 /home/vagrant/Code/test-api/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /home/vagrant/Code/test-api/vendor/illuminate/container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /home/vagrant/Code/test-api/vendor/illuminate/container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#15 /home/vagrant/Code/test-api/vendor/illuminate/container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#16 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(373): Illuminate\\Container\\Container->call(Array, Array)
#17 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(339): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#18 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(313): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\v1\\MessageController), 'create', Array)
#19 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(275): Laravel\\Lumen\\Application->callControllerAction(Array)
#20 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(255): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#21 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#23 /home/vagrant/Code/test-api/app/Http/Middleware/AuthMiddleware.php(52): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(151): App\\Http\\Middleware\\AuthMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'user')
#25 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#27 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(256): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#30 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(160): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#33 /home/vagrant/Code/test-api/vendor/neomerx/cors-illuminate/src/CorsMiddleware.php(67): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(151): Neomerx\\CorsIlluminate\\CorsMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))
#37 /home/vagrant/Code/test-api/vendor/illuminate/pipeline/Pipeline.php(104): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(410): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#39 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#40 /home/vagrant/Code/test-api/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(107): Laravel\\Lumen\\Application->dispatch(NULL)
#41 /home/vagrant/Code/test-api/public/index.php(28): Laravel\\Lumen\\Application->run()
#42 {main}
"} 
```

### Steps To Reproduce:
Use Laravel Notifications.

**Comment by georgeboot** [comment]
You can word around this by adding ramsey/uuid manually: `composer require ramsey/uuid`

I don't think Laravel Notifications is officially supported by Lumen, so I don't think the team wil fix this issue soon (if at all).

**Comment by driesvints** [comment]
Yeah, just do a `composer require ramsey/uuid` like @georgeboot suggested. It's not included by default with lumen.

**Comment by paxperscientiam** [comment]
> Yeah, just do a `composer require ramsey/uuid` like @georgeboot suggested. It's not included by default with lumen.

To anyone else who stumbled into this thread like me, this is the case with the illuminate/support package itself too.

**Comment by brunoosella** [comment]
NOT WORKING
